
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:10.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Pack
          command: |
            PACKAGE_FILE=$(npm pack | tail -1)
            mkdir -p package
            mv $PACKAGE_FILE package/
      - store_artifacts:
          path: ~/repo/package
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/
            - build/
            - node_modules/
            - package.json
  test:
    working_directory: ~/repo
    docker:
      - image: node:10.14.1
      - image: mongo:4.0.1
    environment:
      - MONGO_URL: "mongodb://localhost:27017"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            sed -i '/"\*\*\/\*\.spec\.ts"/d' ./tsconfig.json
            npm run build
            npm test
  deploy:
    working_directory: ~/repo
    docker:
      - image: node:10.14.1
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" >> ~/.npmrc
            npm publish
            echo "Successfully published to NPM"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy:
          context: npm_deployment
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
